#!/bin/sh
#
#

while true; do
    /usr/bin/pharos-release-station
    if [ $? -ne 0 ]; then
      	zenity --error --text="An error occurred during the previous session. Restarting..."
    else
	exit 0
    fi
done	
