#!/bin/sh
#
#

while true; do
    /usr/lib/pharos-release-station/release-station
    [ $? -eq 128 ] && continue
    if [ $? -ne 0 ]; then
      	zenity --error --text="An error occurred during the previous session. Restarting..."
    else
	exit 0
    fi
done	
