#!/bin/sh
#
#

while true; do
    /usr/lib/pharos-release-station/release-station
    rv=$?
    [ $rv -eq 128 ] && continue
    [ $rv -eq 0 ] && exit 0
    zenity --error --text="An error occurred during the previous session. Restarting..."
done	
